### ISSUE TITLE
Syntax highlighting for headings

### ISSUE THREAD

**Issue by gwax** [Lukasa/language-restructuredtext#56]
Right now headings are not highlighted and only have the scope `text.restructuredtext`. Please add additional scopes to allow syntax highlighting: `heading.markup.restructuredtext` for all headings, and `heading-#.restructuredtext` where `#` is the pertinent numbered heading.

**Comment by Alhadis** [comment]
👋 Hey @gwax,

This is impossible for two reasons, both of which relate to limitations in the syntax highlighting engine used by Atom:

1. __It's impossible for the engine to process more than one line at a time.__
This is done for speed: with every change a user makes, the document needs to be reprocessed, and being able to do this from an arbitrary location helps performance.

2. __The engine has no concept of state.__
Since the order in which section markers appear determines a document's hierarchy, the highlighting engine must "remember" which characters denote top-level headings, subheadings, tertiary headings, and so forth. We can't assume that `======` will always represent `heading-1`, `--------` represent `heading-2`, as it is in Markdown.

I know it's a pain. Lightweight markup languages like AsciiDoc and reStructuredText are the worst affected by the highlighting engine's limitations. :(

**Comment by gwax** [comment]
Bummer.

Thank you @Alhadis for the very clear and detailed response to my issue.
