### ISSUE TITLE
Use of "<<" permanently turns on monospaced highlighting

### ISSUE THREAD

**Issue by andy-maier** [Lukasa/language-restructuredtext#71]
Consider the following example .rst file:

```
Paragraph 1

``monospaced``

.. code-block:: sh

    $ cat >py.sh <<EOT
    #!/bin/bash
    py=$(which python)
    $py "$@"
    EOT

``monospaced``

Paragraph 2
```

Atom when using this package highlights this incorrectly. Anything after the `<<` gets highlighted in green (same as text in double backquotes). Usage of double backquotes after that does not reset this highlighting.

Screen shot how the above file is highlighted:

<img width="316" alt="Screenshot 2021-12-14 at 11 40 46" src="https://user-images.githubusercontent.com/8939758/145983273-b0ab6a09-637f-42b5-af32-dad19ce88a4a.png">

When I remove one of the two `<` characters, the highlighting is correct again, so this is clearly triggered by the presence of two `<<`:

<img width="316" alt="Screenshot 2021-12-14 at 11 43 25" src="https://user-images.githubusercontent.com/8939758/145983488-f5cab0c5-ca3a-4532-a857-dd107e6b0383.png">

**Comment by Alhadis** [comment]
👋 Hey mate, sorry for the slow response.

This is actually the fault of Atom's shell-script grammar: specifically, the rules responsible for matching here-docs. A ~~workaround~~ _hack_ is to use `..` as a here-doc delimiter instead of `EOT`:

~~~restructuredtext
.. code-block:: sh

	$ cat >py.sh <<..
	#!/bin/bash
	py=$(which python)
	$py "$@"
	..
..

`Link <link.html>`_

~~~

This works because `..` [introduces a comment](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#comments) in reStructuredText, while the embedded shell-script continues behaving as if it were written like this:

~~~shell
#!/bin/sh
set -e

# Note the strange indentation below: this is what Atom's
# shell grammar sees when it highlights the "indented"
# code-sample in reStructuredText:
    cat >py.sh <<END
    #!/bin/bash
    py=$(which python)
    $py "$@"
END
~~~

This could've been fixed on Atom's end, had I responded before they announced the [editor's retirement](https://github.blog/2022-06-08-sunsetting-atom/) by end-of-year.
